version: '3'

services:
  db-postgres-natubanho:
    image: postgres:alpine
    ports:
      - "5435:5433"
    container_name: "db-postgres-natubanho"
    restart: always
    volumes:
      - ./banco-de-dados-natubanho:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admuser
      POSTGRES_PASSWORD: admuser
volumes:
  banco-de-dados-natubanho: